wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STR-SSDM.01-2018-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-BB.REG_OUT01-2018-OAS-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STR-CYB_GUIDE.01-2018-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-BB.GDI_AP-2018-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PHCB-CAP_BLD.02-2018-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-BB.POW_ECO-2018-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-BB.5G_01-2018-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STR-DIGITAL.01-2018-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-BB.ID01-2018-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-GEN-E_WASTE.02-2018-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PHCB-CAP_BLD.01-2018-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-GEN-EUROPE.01-2018-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-GEN-EUROPE.02-2018-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STR-E_HEALTH.13-2018-JPG-S.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STR-M_POWER.01-2018-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-EF.BDR-2018-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-WTID.OL-2018-OAS-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-ICTOI-2018-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-EF.MIR03-2018-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-LDC-LLDC_AM.02-2018-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-LDC-LLDC_AM.01-2018-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STR-E_HEALTH.11-2018-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STR-E_HEALTH.12-2018-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-EF.CS_NICARAGUA-2018-JPG-S.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-BB.REG_OUT03-2018-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STR-E_AGRICULT.02-2018-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-LDC-ICTLDC-2018-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-WTID-2018-E06-USB-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-ICT_PRICES.01-2017-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-TDC-WTDC-2017-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-GEN-E_WASTE.01-2017-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-YB-2017-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-BB.QOS_REG01-2017-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-EF.APP_ECO_AFRICA-2017-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-WTID.OL-2017-OAS-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-ICTOI-2017-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.02.2-2017-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-EF.CS_PANAMA-2017-JPG-S.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG01.08.1-1-2017-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.01.1-2017-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.03.1-2017-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.04.1-2017-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.05.1-2017-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.06.1-2017-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.07.1-2017-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.08.1-2017-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.09.1.4-2017-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG01.07.4-2017-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG01.05-2017-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG01.03.1-2017-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG01.04.1-2017-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG01.06.3-2017-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG01.08.1-2017-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG01.RES09.2-2017-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG01.01.1-2017-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG01.02.1-2017-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-GEN-ICT_SDGS.01-2017-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SPEC-2017-V5.1-DVD-JPG-M07.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STR-GCI.01-2017-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/BDT-REPORT-LIBERIACALLDETAILRECORD-2017-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/BDT-REPORT-SIERRALEONECALLDETAILRECORD-2017-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/BDT-REPORT-GUINEACALLDETAILRECORD-2017-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-BB.REG_OUT01-2017-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-BB.GDI_01-2017-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-WTID-2017-OAS-USB-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PHCB-CAP_BLD.01-2017-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-EF.CS_BOLIVIA-2017-JPG-S.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-ICTOI-2016-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-TTR.17-2016-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-EF.GILARDI-2016-JPG-S.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-YB-2016-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-LDB-2016-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-BB.REG_OUT02-2016-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-EF.ONA-2016-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-EF.RAD_SPEC_GUIDE-2016-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STR-E_HEALTH.09-2016-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-EF.CS_PARAGUAY-2016-JPG-S.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STR-E_AGRICULT.01-2016-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/BDT-REPORT-STRATEGYYOUTHEMPLOYMENT-1998-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/BDT-REPORT-MPOWERINGDEVINITIATIVE-2016-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STR-SSDM.01-2016-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-WTID.OL-2016-OAS-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-TTR.16-2015-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-ICTOI-2015-R1-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-YB-2015-R1-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-LDB-2015-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SPEC-2015-V5.0-DVD-JPG-M07.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-EF.CS_DOMINICA-2015-JPG-S.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STR-SECU-2015-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STR-CYB_CRIME-2015-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D012A00009C4D01JPGE.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D012A0000964D01JPGS.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STR-M_POWER.01-2015-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STR-SSDM.01-2015-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-WTID-2015-OAS-CD-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D012A00009E4D01JPGE.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PHCB-SIS_A.01-2014-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STR-E_HEALTH.07-2014-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-HDB-GUIDELINES.01-2014-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-THEM.15-2014-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-EF.PG.BENCH-2014-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-BB.RPT5-2014-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-EF.BB.ANDEAN-2014-JPG-S.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-EF.REG.ROAMING-2014-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-THEM.14-2014-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-THEM.13-2014-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-YB-2014-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D012A0000984D01JPGE.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D012A0000974D01JPGE.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D012A0000944D01JPGS.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D012A00009B4D01JPGE.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-ICTOI-2014-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-TDC-WTDC-2014-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STR-M_POWER.01-2014-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-LDB-2014-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-TTR.15-2014-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-ITCMEAS-2014-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STR-E_HEALTH.06-2014-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.11.3-2014-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.22.1-2014-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG01.07.3-2014-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG01.19.2-2014-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.26-2014-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/BDT-WTDC-2014-ACHIEVEMENTS-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG01.24-2014-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.09.3.2-2014-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.RES09.1-2014-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.25-2014-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG01.22.1-2014-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG01.18.2-2014-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.17.3-2014-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG01.12.3-2014-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.10.3-2014-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D012A0000774D01JPGE.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D012A0000734D01JPGE.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SPEC-2014-V4.1-DVD-JPG-M03.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG01.20.1-2014-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.24-2014-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.14.3-2014-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG01.10.3-2014-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG01.23-2014-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-THEM.17-2013-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-THEM.16-2013-JPG-F.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-EF.IIC.CAR-2013-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-EF.SERV_FUND-2013-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-EF.IMR02-2013-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-EF.COMPREG-2013-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-EF.IIC.AFR-2013-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D012A00006E4D01JPGE.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-YB-2013-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-ICTOI-2013-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-EF.TAX-2013-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D012A00006D4D01JPGE.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D012A0000664D01JPGE.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-EF.NGN-2013-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-EF.IMR-2013-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D012A0000694D01JPGE.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D012A0000674D01JPGE.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-TTR.14-2013-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D012A0000604D01JPGE.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-THEM.05-2013-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D012A0000474D01JPGE.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D012A0000514D01JPGE.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D012A0000494D01JPGE.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-HDB-GUIDELINES.01-2012-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PHCB-SIS_A.02-2012-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-BB.CS4-2012-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STR-E_HEALTH.05-2012-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-THEM.10-2012-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-THEM.11-2012-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-THEM.07-2012-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-BB.CS5-2012-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-BB.CS7-2012-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-BB.CS6-2012-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-THEM.03-2012-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-THEM.01-2012-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-THEM.06-2012-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-THEM.04-2012-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-THEM.02-2012-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-BB.CS1-2012-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-BB.CS2-2012-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-BB.CS3-2012-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-BB.CS8-2012-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-YB-2012-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D012A0000424D01JPGE.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D012A0000394D01JPGE.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D012A0000374D01JPGE.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D012A0000364D01JPGE.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D012A0000354D01JPGE.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-TTR.13-2012-CD-JPG-M.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-GEN-CONNECT.AM-2012-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-AR-2012-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SPEC-2012-V4.0-CD-JPG-M03.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D012A00002D4D01JPGE.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-BB.RPT1-2012-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-BB.RPT2-2012-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-BB.RPT3-2012-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-BB.RPT4-2012-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-GEN-CONNECT.ARB-2012-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D012A00001E4D01JPGE.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-ICTOI-2012-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PHCB-SIS_A.03-2011-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-THEM.09-2011-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-EF.STATMOD-2011-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-THEM.08-2011-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-THEM.12-2011-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-TRH.1-2011-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-ITC_IND_HBK-2011-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-GEN-OVW-2011-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D012A0000194D01JPGE.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-YB-2011-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STR-GOV.M_GOV-2011-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-ICTOI-2011-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-MEAS_WSIS-2011-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-LDC-ICTLDC.2011-2011-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-LDC-ICTLDC.2000.2010-2011-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STR-E_HEALTH.03-03-2011-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.RES09-2010-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STR-E_HEALTH.04-11-2010-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.FEES-1-2010-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-TTR.12-2010-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-HDB-GSP-2010-1-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-YB-2010-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-HDB-UNIVERSA;-2010-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-COP.01-11-2010-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STR-ENV.E_ENV-11-2010-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STR-GOV.E_GOV-11-2010-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-TDC-WTDC-2010-R1-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-GEN-OVW-2010-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STR-E_HEALTH.03-2010-09-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-ICT_CORE-2010-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.18.1-2010-1-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.10.2-2010-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG01.06.2-2010-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-HDB-GUIDELINES.01-2010-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.11.2-2010-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.22-2010-01-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-WTDR-2010-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.14.2-2010-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-ICTOI-2010-R1-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.22-2010-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STR-E_HEALTH.03-2010-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG01.12.2-2010-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG01.18.1-2010-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.17.2-2010-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG01.10.2-2010-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.09.2-2010-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.19.1-2010-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG01.19.1-2010-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG01.21-2010-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG01.22-2010-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.20.2-2010-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG01.20-2010-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG01.07.2-2010-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-EF.NGN.CS-2009-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-EF.MTR-2009-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-EF.ACCOUNT-2009-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-TTR.11-2009-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-RPM.AM-2009-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-YB-2009-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-RPM.AR-2009-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-RPM.EUR-2009-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SPEC-2009-V3.0-CD-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-RPM.CIS-2009-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-RPM.AF-2009-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-RPM.AP-2009-R1-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-ICTOI-2009-R1-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-ITCMEAS-2009-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STR-SI_IN-2009-JPG-A.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-EF.TARIFFREG-2008-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-EF.BB.LATAM-2008-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-TTR.10-2008-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-AF-2008-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-LDC-HRD.ICTSURV-2008-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-LDC-HR_AFR_E-2008-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-ICT_YOUTH-2008-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STR-ENV.CLIMATE-2008-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-YB-2008-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-AP-2008-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-EF.POL.LATAM-2007-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STR-SECU-2007-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-HDB-WET-2007-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-TTR.9-2007-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-LDC-ICTEARII-2007-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-YB-2007-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-HDB-VPD-2007-R1-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-GEN-OVW-2007-E09-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.14.1-2006-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-TTR.8-2006-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STR-SECU-2006-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-EF.TEF2-2006-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SPEC-2006-V1.1-CD-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-LDC-WRKSP-2006-JPG-F.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.20.1-2006-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.10.1.2-2006-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-WTDR-2006-R1-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-TDC-WTDC-2006-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.10.1-2006-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.09.3.1-2006-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.11.1-2006-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-LDC-ICTLDC.2001.2006-2006-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.09.1.2-2006-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STR-EMPW_DVLP-2006-1.01-JPG-F.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.21-2006-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG01.07.1-2006-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STR-CRIM-2006-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.09.1.3-2006-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.18-1-2006-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG01.18-2006-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG01.10.1-2006-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG01.19-2006-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG01.06.1-2006-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.18-2006-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG01.17-2006-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-ICTOI-2006-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-YB-2006-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-MISC.2-2005-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-AM-2005-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-HDB-IP-2005-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-YB-2005-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-EF.COSTMOD.LATAM-2004-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-EF.CST1-2004-CD-JPG-M03.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-TTR.7-2004-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-HDB-IPT-2004-R1-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-WTI-2004-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-HDB-HET-2004-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-YB-2004-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-LDC-ICTLDC-2004-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-AF-2004-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-AP-2004-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-EF.FINICT-2003-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-EF.IPPRICE-2003-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-TTR.6-2003-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-WTDR-2003-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-EF.INVST-2003-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-YB-2003-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.16.2.1-2002-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-TTR.5-2002-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG01.10-2002-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG01.12-2002-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG01.15-2002-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.16-2002-P3-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.17-2002-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.16.2-2002-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG01.07-2002-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG01.13-2002-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.09-2002-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.09.1-2002-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.09.2-2002-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.12-2002-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.14-2002-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.16-2002-P1-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.16-2002-P2-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-RUR-2002-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-TDC-WTDC-2002-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-IDSEA-2002-CD-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-WTDR-2002-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-AP-2002-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-QSG1.2-2002-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-TTR.4-2001-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.16.1-2001-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.09.3-2001-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-EF.TEF1-2001-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-WTI-2001-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-HDB-TDG-2001-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-RUR-2001-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-TTR.3-2000-CD-JPG-M07.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-ITD.3-2000-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-AM-2000-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-AP-2000-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-TTR.2-1999-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-HDB-GMPCS-1999-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-ITD.2-1999-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-EF.FINI-1999-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-TDM-1999-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-DOT-1999-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-WTDR-1999-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-TTR.1-1998-V6-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-TTR.1-1998-V5-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-TTR.1-1998-V3-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-TTR.1-1998-V1-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-TTR.1-1998-V0-P1-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-TTR.1-1998-V4-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-TTR.1-1998-V2-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/BDT-WTDC-1998-FINALREPORT-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-QSG1.2-1998-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-PREF-ITD.1-1998-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.08-1998-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG01.01-1998-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG01.03-1998-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.01-1998-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.03-1998-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG01.04-1998-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.02-1998-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG01.02-1998-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.02.1-1998-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.04-1998-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.05-1998-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.06-1998-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-SG02.07-1998-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-WTDR-1998-JPG-F.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-HDB-MCD-1997-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-STG-TDM-1997-JPG-M03.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-WTDR-1997-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-TDC-AR-1996-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-TDC-AF-1996-JPG-E.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/D-IND-AR-1996-JPG-M03.jpg
wget https://www.itu.int/itu-d/apis/clients/publications/res/image/BDT-WTDC-1994-FINALREPORT-JPG-E.jpg
